AWSTemplateFormatVersion: 2010-09-09
Description: Template for the DSpace Application Load Balancer
# borrowed from https://github.com/jaroslaw-bagnicki/aws-w-praktyce/blob/4fb5a7e491305afea72ab22b87cfcad0909b4e29/08/memes-generator/network/templates/load-balancing.yaml 

# docs:
# https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-resource-elasticloadbalancingv2-loadbalancer.md

#TODO: revise the parameters to match my existing style
#TODO: create any required security groups for this load balancer

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  AlbSecurityGroup:
    Description: Reference of the AlbSecurityGroup from the SSM
    Type: AWS::SSM::Parameter::Value<String>
  PublicSubnetAId:
    Description: Reference of the PublicSubnetAId from the SSM
    Type: AWS::SSM::Parameter::Value<String>
  PublicSubnetBId:
    Description: Reference of the PublicSubnetBId from the SSM
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: !Sub ${Project}-${Stage}-${Component}-alb # Remove Component if Name is too long
      SecurityGroups:
        - !Ref AlbSecurityGroup
      Subnets:
        - !Ref PublicSubnetAId
        - !Ref PublicSubnetBId
      Type: application
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-alb

  LoadBalancerParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component}-LoadBalancerArn
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/alb/arn
      Value: !Ref LoadBalancer
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-alb-arn

  LoadBalancerUrlParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component}-LoadBalancerUrl
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/alb/url
      Value: !GetAtt LoadBalancer.DNSName
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-alb-url

Outputs:
  LoadBalancer:
    Description: The Arn of LoadBalancer
    Value: !Ref LoadBalancer
  LoadBalancerParamName:
    Description: The name of the SSM parameter where the Arn of the LoadBalancer is stored
    Value: !Ref LoadBalancerParam
  LoadBalancerUrl:
    Description: The URL of the ALB
    Value: !GetAtt LoadBalancer.DNSName
  LoadBalancerUrlParamName:
    Description: The name of the SSM parameter where the Arn of the LoadBalancerUrl is stored
    Value: !Ref LoadBalancerUrlParam