---
AWSTemplateFormatVersion: "2010-09-09"

Description: DSpace API EC2 instance

# TODO: provision this EC instance using Ansible-pull: https://www.google.com/amp/s/hangarau.space/automatically-configuring-ec2-instance-from-cloudformation-using-ansible-in-pull-mode/amp/

Metadata:
  License: 'BSD 3-Clause'

Parameters:
  EnvType:
    Description: Environment type.
    Default: dev
    Type: String
    AllowedValues: [prd, dev, stg]
    ConstraintDescription: must specify prd, dev, or stg.
  KeyName:
      ConstraintDescription: must be the name of an existing EC2 KeyPair.
      Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
      Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - t3.small
    - t3.medium
    - t3.large
    - m1.small
    - m1.medium
    - m1.large
    - m1.xlarge
    - m2.xlarge
    - m2.2xlarge
    - m2.4xlarge
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge
    - c1.medium
    - c1.xlarge
    - c3.large
    - c3.xlarge
    - c3.2xlarge
    - c3.4xlarge
    - c3.8xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    - g2.2xlarge
    - g2.8xlarge
    - r3.large
    - r3.xlarge
    - r3.2xlarge
    - r3.4xlarge
    - r3.8xlarge
    - i2.xlarge
    - i2.2xlarge
    - i2.4xlarge
    - i2.8xlarge
    - d2.xlarge
    - d2.2xlarge
    - d2.4xlarge
    - d2.8xlarge
    - hs1.8xlarge
    - cr1.8xlarge
    - cc2.8xlarge
    ConstraintDescription: must be a valid EC2 instance type, with oomph
    Default: t3.large
    Description: DSpace API Server EC2 instance type
    Type: String
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: A list of subnet IDs where the load balancer will be created
  DSpaceApiAmi:
    ConstraintDescription: must be a valid AMI, to which we have permissions to use
    Default: ami-003203a9ddedb9900
    Description: AMI ID to use for this DSpace API Instance
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
  CDLprogram:
    Default: pub
    Description: three-letter designation of the CDL program that owns this instance
    Type: String
  CDLservice:
    Default: dspace
    Description: designation for the service this instance provides
    Type: String
  function:
    Default: api
    Description: designation for the function or purpose of this instance
    Type: String

Resources:
  DSpaceAPIServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'DSpaceApiAmi'
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !ImportValue DSpaceApiInstanceSecurityGroup
          SubnetId: !Select [ 0, !Ref SubnetIds ]
      Tags: 
        - Key: "Program"
          Value: !Ref 'CDLprogram'
        - Key: "Service"
          Value: !Ref 'CDLservice'
        - Key: "Environment"
          Value: !Ref 'EnvType'
        - Key: "Name"
          Value: !Join
            - '-'
            - - !Ref 'CDLprogram'
              - !Ref 'CDLservice'
              - !Ref 'function'
              - !Ref 'EnvType'

Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'DSpaceAPIServer'
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt [DSpaceAPIServer, AvailabilityZone]
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt [DSpaceAPIServer, PublicDnsName]
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [DSpaceAPIServer, PublicIp]
