---
  AWSTemplateFormatVersion: '2010-09-09'
  Parameters:
    EnvType:
      Description: Environment type (e.g. prod, stage, dev)
      Type: String
    CDLprogram:
      Description: Name of the CDL program
      Type: String
    CDLservice:
      Description: Name of the CDL service
      Type: String
    VpcId:
      Description: ID of the VPC that the instances will be launched in
      Type: AWS::EC2::VPC::Id
    SubnetIds:
      Description: Comma-separated list of subnet IDs to launch the instances in
      Type: List<AWS::EC2::Subnet::Id>
    SecurityGroupId:
      Description: ID of the security group that allows inbound traffic to the instances
      Type: AWS::EC2::SecurityGroup::Id
    KeyName:
      Description: Name of the EC2 key pair to use for SSH access to the instances
      Type: AWS::EC2::KeyPair::KeyName
    InstanceType:
      Description: Instance type for the EC2 instances
      Type: String
      Default: t2.micro
      AllowedValues:
        - t2.micro
        - t2.small
        - t2.medium
    AMI:
      Description: ID of the AMI to use for the EC2 instances
      Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
      Default: /aws/service/amazon-linux-ami.latest.amazon-linux-2-x86_64
    SSLCertificateArn:
      Description: ARN of the SSL certificate for HTTPS listener
      Type: String
  
  TODO: Add any additional parameters needed for the load balancer and reverse proxy setup
  