name: Lint
on:
  push:
    # only trigger on branches, not tags
    branches: '**'
  pull_request:
    # we only want to lint PRs to main
    branches: [ main ]
jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2
      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint *.yaml
